## 3.1.1 넘파이 기본

In [2]:
import numpy as np
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
A.shape

(2, 2)

In [26]:
print(A.mean(), A.max(), A.min(), A.sum())

2.5 4 1 10


In [6]:
A.dtype

dtype('int32')

## 3.1.3 원소 선택

In [7]:
print(A[0])

[1 2]


아래 두 가지 방법은 서로 동일하다

In [11]:
print(A[0][0])

1


In [10]:
print(A[0, 0])

1


조건에 맞는 원소들만 인덱싱

In [12]:
A[A>1]

array([2, 3, 4])

## 3.1.4 배열 형태 바꾸기

- transpose() : 전치, 대각선을 기준으로 변경

In [13]:
A

array([[1, 2],
       [3, 4]])

In [18]:
A.transpose() # == A.T

array([[1, 3],
       [2, 4]])

- flatten() : 평탄화, 다차원 배열 -> 1차원 배열으로 변경

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
A.flatten()

array([1, 2, 3, 4])

## 3.1.5 배열의 연산

같은 크기의 행렬끼리는 사칙연산이 가능함, 동일한 위치에 있는 원소끼리 연산

In [21]:
A

array([[1, 2],
       [3, 4]])

In [22]:
A + A

array([[2, 4],
       [6, 8]])

In [23]:
A - A

array([[0, 0],
       [0, 0]])

In [24]:
A / A

array([[1., 1.],
       [1., 1.]])

In [27]:
A * A

array([[ 1,  4],
       [ 9, 16]])

## 3.1.6 브로드캐스팅

행렬의 크기가 달라도 연산이 가능하게 작은 행렬을 확장해주는 기능

In [29]:
A

array([[1, 2],
       [3, 4]])

In [30]:
B = [10, 100]

In [31]:
A * B

array([[ 10, 200],
       [ 30, 400]])